# Generated by Django 4.1.3 on 2024-05-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
